studentCRUD/urls.py
from django.contrib import admin
from django.urls import path
from student import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('emp', views.emp, name='emp'),
    path('emp', views.emp),
    path('clear', views.clear),
    path('export', views.export),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

student/models.py
from django.db import models

# Django model "Student" stored in the database
class Student(models.Model):
    sid = models.CharField(max_length=2)
    sfname = models.CharField(max_length=15)
    slname = models.CharField(max_length=15)
    gfname = models.CharField(max_length=15)
    glname = models.CharField(max_length=15)
    semail = models.EmailField()
    scontact = models.CharField(max_length=15)
    class Meta:
        db_table = "student"

student/forms.py
from django import forms
from student.models import Student

# Creates the form
class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

student/views.py
from django.shortcuts import render, redirect
from student.forms import StudentForm
from student.models import Student
import csv

# Create your views here.
def emp(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = StudentForm()
    return render(request,'index.html',{'form':form})
def show(request):
    students = Student.objects.all()
    return render(request,"show.html",{'students':students})
def edit(request, id):
    student = Student.objects.get(id=id)
    return render(request,'edit.html', {'student':student})
def update(request, id):
    student = Student.objects.get(id=id)
    form = StudentForm(request.POST, instance = student)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'student': student})
def destroy(request, id):
    student = Student.objects.get(id=id)
    student.delete()
    return redirect("/show")
def export(request):
    students = Student.objects.all()

    with open('record.csv', mode='w', newline='') as record_file:
        record_writer = csv.writer(record_file, skipinitialspace=True, delimiter=',', quotechar='"',
                                        quoting=csv.QUOTE_MINIMAL)
        record_writer.writerow(
            ["Student Grade", "Student First Name", "Student Last Name", "Parent/Guardian First Name", "Parent/Guardian Last Name", "Student Email", "Student Contact"])
        for student in students:
            record_writer.writerow([student.sid, student.sfname, student.slname, student.gfname, student.glname, student.semail, student.scontact])

    return render(request, "show.html", {'students': students})
def clear(request):
    students = Student.objects.all()
    students.delete()
    return render(request, "show.html", {'students': students})

student/templates/edit.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<form method="POST" class="post-form" action="/update/{{student.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Grade:</label>
    <div class="col-sm-4">
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ student.sid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student First Name:</label>
    <div class="col-sm-4">
        <input type="text" name="sfname" id="id_sfname" required maxlength="15" value="{{ student.sfname }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Last Name:</label>
    <div class="col-sm-4">
        <input type="text" name="slname" id="id_slname" required maxlength="20" value="{{ student.slname }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Parent/Guardian First Name:</label>
    <div class="col-sm-4">
        <input type="text" name="gfname" id="id_gfname" required maxlength="15" value="{{ student.gfname }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Parent/Guardian Last Name:</label>
    <div class="col-sm-4">
        <input type="text" name="glname" id="id_glname" required maxlength="20" value="{{ student.glname }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Email:</label>
    <div class="col-sm-4">
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ student.semail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ student.scontact }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

student/templates/index.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<form method="POST" class="post-form" action="/emp">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Grade:</label>
    <div class="col-sm-4">
      {{ form.sid }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student First Name:</label>
    <div class="col-sm-4">
      {{ form.sfname }}
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Last Name:</label>
    <div class="col-sm-4">
      {{ form.slname }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Parent/Guardian First Name:</label>
    <div class="col-sm-4">
      {{ form.gfname }}
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Parent/Guardian Last Name:</label>
    <div class="col-sm-4">
      {{ form.glname }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Email:</label>
    <div class="col-sm-4">
      {{ form.semail }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Student Contact:</label>
    <div class="col-sm-4">
      {{ form.scontact }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

student/templates/show.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Records</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Student Grade</th>
        <th>Student First Name</th>
        <th>Student Last Name</th>
        <th>Parent/Guardian First Name</th>
        <th>Parent/Guardian Last Name</th>
        <th>Student Email</th>
        <th>Student Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for student in students %}
    <tr>
        <td>{{ student.sid }}</td>
        <td>{{ student.sfname }}</td>
        <td>{{ student.slname }}</td>
        <td>{{ student.gfname }}</td>
        <td>{{ student.glname }}</td>
        <td>{{ student.semail }}</td>
        <td>{{ student.scontact }}</td>
        <td>
            <a href="/edit/{{ student.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ student.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/emp" class="btn btn-primary"> Add New Record </a>
        <a href="/export" class="btn btn-success">Export Set To CSV</a>
        <a href="/clear" class="btn btn-danger">Clear All Record</a></center>
</body>
</html>